// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVDzOqK_R9VnvZ6OBYJI9w4CGkbZDYrkU',
    appId: '1:700757427001:web:3c7e101ebb3f0c4d351ee8',
    messagingSenderId: '700757427001',
    projectId: 'pocketfridge-392',
    authDomain: 'pocketfridge-392.firebaseapp.com',
    storageBucket: 'pocketfridge-392.firebasestorage.app',
    measurementId: 'G-9VTZVSNBC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATUBXiDlbYsMSGiBXJ5Q1d5vVsjXowWYM',
    appId: '1:700757427001:android:eff04308f99b0bda351ee8',
    messagingSenderId: '700757427001',
    projectId: 'pocketfridge-392',
    storageBucket: 'pocketfridge-392.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC00NVz5sdGES4ZDA_x-Cv2KIh4Aw-WK8w',
    appId: '1:700757427001:ios:6ae5c1e782b32562351ee8',
    messagingSenderId: '700757427001',
    projectId: 'pocketfridge-392',
    storageBucket: 'pocketfridge-392.firebasestorage.app',
    iosBundleId: 'fr.remipocket.pocketFridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC00NVz5sdGES4ZDA_x-Cv2KIh4Aw-WK8w',
    appId: '1:700757427001:ios:6ae5c1e782b32562351ee8',
    messagingSenderId: '700757427001',
    projectId: 'pocketfridge-392',
    storageBucket: 'pocketfridge-392.firebasestorage.app',
    iosBundleId: 'fr.remipocket.pocketFridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVDzOqK_R9VnvZ6OBYJI9w4CGkbZDYrkU',
    appId: '1:700757427001:web:71e72550cf143df3351ee8',
    messagingSenderId: '700757427001',
    projectId: 'pocketfridge-392',
    authDomain: 'pocketfridge-392.firebaseapp.com',
    storageBucket: 'pocketfridge-392.firebasestorage.app',
    measurementId: 'G-D5BKZN5ZS6',
  );
}
